[version]
min = "0.1.0"
max = "0.1.0"

[toolchain.fortran]
compiler = "/opt/homebrew/bin/gfortran"

[toolchain.c]
compiler = "/opt/homebrew/opt/llvm/bin/clang"

[toolchain.cpp]
compiler = "/opt/homebrew/opt/llvm/bin/clang++"

[toolchain.cmake]
generator = "ninja"

[backend.use]
gkeyll = true
hermes3 = true

[backend.install]
prefix = "~/tmp/Ymir"

[backend.config.gkeyll]
root = "~/tmp/Ymir/repo/gkeyll"

[backend.config.hermes3]
root = "~/tmp/Ymir/repo/hermes-3"

[[simulation.case]]
backend = "gkeyll"
name = "1X2V_Sheath_BGK"
input = [ "1X2V_Sheath_BGK.lua" ]
